// Auto-generated by LibreLane
module DigitalSine(
`ifdef USE_POWER_PINS
  inout DVSS,
  inout DVDD,
`endif
  input rst,
  input clk,
  output sign,
  output signB,
  output[17:0] sine_out
);
endmodule
