// Auto-generated by LibreLane
module DigitalSine(
`ifdef USE_POWER_PINS
  inout DVSS,
  inout DVDD,
`endif
  input rst,
  input clk,
  output o_sign,
  output o_signB,
  output[17:0] DATA
);
endmodule
