// Auto-generated by LibreLane
module DigitalSine(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input rst,
  input clk,
  output sign,
  output signB,
  output[32:0] sine_out
);
endmodule
