/* Generated by Yosys 0.62 (git sha1 7326bb7d6641500ecb285c291a54a662cb1e76cf, clang++ 21.1.2 -fPIC -O3) */

module DigitalSine(rst, clk, sign, signB, sine_out);
  input rst;
  wire rst;
  input clk;
  wire clk;
  output sign;
  wire sign;
  output signB;
  wire signB;
  output [17:0] sine_out;
  wire [17:0] sine_out;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire \CTRL.P0 ;
  wire \CTRL.P1 ;
  wire \CTRL.S0 ;
  wire \DPATH.SUM.Cout0 ;
  wire \DPATH.SUM.fa_1.A ;
  wire \DPATH.SUM.fa_1.S ;
  wire \DPATH.SUM.fa_2.A ;
  wire \DPATH.SUM.fa_2.S ;
  wire \DPATH.SUM.fa_3.A ;
  wire \DPATH.SUM.fa_3.S ;
  wire \DPATH.SUM.fa_4.A ;
  wire \DPATH.SUM.fa_4.S ;
  wire \DPATH.SUM.fa_5.A ;
  wire \DPATH.SUM.fa_5.S ;
  wire \DPATH.SUM.fa_6.A ;
  wire \DPATH.SUM.fa_6.S ;
  wire \DPATH.SUM.ha_0.S ;
  sg13g2_inv_1 _138_ (
    .A(\DPATH.SUM.fa_3.A ),
    .Y(_100_)
  );
  sg13g2_inv_1 _139_ (
    .A(\DPATH.SUM.fa_5.A ),
    .Y(_101_)
  );
  sg13g2_inv_1 _140_ (
    .A(\DPATH.SUM.fa_2.A ),
    .Y(_102_)
  );
  sg13g2_inv_1 _141_ (
    .A(\DPATH.SUM.Cout0 ),
    .Y(\DPATH.SUM.ha_0.S )
  );
  sg13g2_inv_1 _142_ (
    .A(sign),
    .Y(signB)
  );
  sg13g2_inv_1 _143_ (
    .A(rst),
    .Y(_000_)
  );
  sg13g2_or2_1 _144_ (
    .A(\DPATH.SUM.fa_5.A ),
    .B(\DPATH.SUM.fa_6.A ),
    .X(_103_)
  );
  sg13g2_nor2_1 _145_ (
    .A(\DPATH.SUM.fa_3.A ),
    .B(\DPATH.SUM.fa_4.A ),
    .Y(_104_)
  );
  sg13g2_nor2_1 _146_ (
    .A(\DPATH.SUM.fa_1.A ),
    .B(\DPATH.SUM.Cout0 ),
    .Y(_105_)
  );
  sg13g2_nor2_1 _147_ (
    .A(_102_),
    .B(_105_),
    .Y(_106_)
  );
  sg13g2_o21ai_1 _148_ (
    .A1(\DPATH.SUM.fa_1.A ),
    .A2(\DPATH.SUM.Cout0 ),
    .B1(\DPATH.SUM.fa_2.A ),
    .Y(_107_)
  );
  sg13g2_nand2_1 _149_ (
    .A(_104_),
    .B(_107_),
    .Y(_108_)
  );
  sg13g2_a21oi_1 _150_ (
    .A1(\DPATH.SUM.fa_5.A ),
    .A2(_108_),
    .B1(\DPATH.SUM.fa_6.A ),
    .Y(sine_out[9])
  );
  sg13g2_nand2_1 _151_ (
    .A(\DPATH.SUM.fa_5.A ),
    .B(\DPATH.SUM.fa_4.A ),
    .Y(_109_)
  );
  sg13g2_inv_1 _152_ (
    .A(_109_),
    .Y(_110_)
  );
  sg13g2_nand2b_1 _153_ (
    .A_N(\DPATH.SUM.fa_6.A ),
    .B(_109_),
    .Y(_111_)
  );
  sg13g2_nor2_1 _154_ (
    .A(\DPATH.SUM.fa_2.A ),
    .B(\DPATH.SUM.fa_1.A ),
    .Y(_112_)
  );
  sg13g2_or2_1 _155_ (
    .A(\DPATH.SUM.fa_2.A ),
    .B(\DPATH.SUM.fa_1.A ),
    .X(_113_)
  );
  sg13g2_nor2_1 _156_ (
    .A(_100_),
    .B(_112_),
    .Y(_114_)
  );
  sg13g2_or2_1 _157_ (
    .A(\DPATH.SUM.fa_2.A ),
    .B(\DPATH.SUM.Cout0 ),
    .X(_115_)
  );
  sg13g2_and2_1 _158_ (
    .A(\DPATH.SUM.fa_5.A ),
    .B(_115_),
    .X(_116_)
  );
  sg13g2_a21oi_1 _159_ (
    .A1(_114_),
    .A2(_116_),
    .B1(_111_),
    .Y(sine_out[10])
  );
  sg13g2_nand2_1 _160_ (
    .A(\DPATH.SUM.ha_0.S ),
    .B(_112_),
    .Y(_117_)
  );
  sg13g2_or2_1 _161_ (
    .A(\DPATH.SUM.fa_3.A ),
    .B(\DPATH.SUM.fa_6.A ),
    .X(_118_)
  );
  sg13g2_o21ai_1 _162_ (
    .A1(_117_),
    .A2(_118_),
    .B1(_111_),
    .Y(sine_out[11])
  );
  sg13g2_nand2_1 _163_ (
    .A(\DPATH.SUM.fa_2.A ),
    .B(\DPATH.SUM.Cout0 ),
    .Y(_119_)
  );
  sg13g2_and2_1 _164_ (
    .A(\DPATH.SUM.fa_2.A ),
    .B(\DPATH.SUM.fa_1.A ),
    .X(_120_)
  );
  sg13g2_inv_1 _165_ (
    .A(_120_),
    .Y(_121_)
  );
  sg13g2_nor2_1 _166_ (
    .A(\DPATH.SUM.ha_0.S ),
    .B(_121_),
    .Y(_122_)
  );
  sg13g2_o21ai_1 _167_ (
    .A1(_118_),
    .A2(_122_),
    .B1(_111_),
    .Y(sine_out[12])
  );
  sg13g2_nor2_1 _168_ (
    .A(_100_),
    .B(_121_),
    .Y(_123_)
  );
  sg13g2_nand2_1 _169_ (
    .A(\DPATH.SUM.fa_3.A ),
    .B(_120_),
    .Y(_124_)
  );
  sg13g2_a21oi_1 _170_ (
    .A1(_110_),
    .A2(_123_),
    .B1(\DPATH.SUM.fa_6.A ),
    .Y(sine_out[13])
  );
  sg13g2_o21ai_1 _171_ (
    .A1(\DPATH.SUM.fa_5.A ),
    .A2(_108_),
    .B1(\DPATH.SUM.fa_6.A ),
    .Y(sine_out[14])
  );
  sg13g2_or2_1 _172_ (
    .A(\DPATH.SUM.fa_5.A ),
    .B(\DPATH.SUM.fa_4.A ),
    .X(_125_)
  );
  sg13g2_o21ai_1 _173_ (
    .A1(_123_),
    .A2(_125_),
    .B1(\DPATH.SUM.fa_6.A ),
    .Y(sine_out[15])
  );
  sg13g2_nor2_1 _174_ (
    .A(\DPATH.SUM.fa_3.A ),
    .B(\DPATH.SUM.fa_5.A ),
    .Y(_126_)
  );
  sg13g2_o21ai_1 _175_ (
    .A1(\DPATH.SUM.ha_0.S ),
    .A2(_121_),
    .B1(_126_),
    .Y(_127_)
  );
  sg13g2_nand3_1 _176_ (
    .A(\DPATH.SUM.fa_6.A ),
    .B(_125_),
    .C(_127_),
    .Y(sine_out[16])
  );
  sg13g2_nand2_1 _177_ (
    .A(_100_),
    .B(_102_),
    .Y(_128_)
  );
  sg13g2_nand2_1 _178_ (
    .A(_102_),
    .B(_104_),
    .Y(_129_)
  );
  sg13g2_nand3_1 _179_ (
    .A(\DPATH.SUM.fa_5.A ),
    .B(\DPATH.SUM.fa_6.A ),
    .C(_129_),
    .Y(sine_out[17])
  );
  sg13g2_nand2_1 _180_ (
    .A(\DPATH.SUM.fa_1.A ),
    .B(\CTRL.S0 ),
    .Y(_130_)
  );
  sg13g2_xnor2_1 _181_ (
    .A(\DPATH.SUM.fa_1.A ),
    .B(\CTRL.S0 ),
    .Y(_131_)
  );
  sg13g2_xnor2_1 _182_ (
    .A(\DPATH.SUM.Cout0 ),
    .B(_131_),
    .Y(\DPATH.SUM.fa_1.S )
  );
  sg13g2_o21ai_1 _183_ (
    .A1(\DPATH.SUM.ha_0.S ),
    .A2(_131_),
    .B1(_130_),
    .Y(_132_)
  );
  sg13g2_and2_1 _184_ (
    .A(\DPATH.SUM.fa_2.A ),
    .B(\CTRL.S0 ),
    .X(_133_)
  );
  sg13g2_xor2_1 _185_ (
    .A(\DPATH.SUM.fa_2.A ),
    .B(\CTRL.S0 ),
    .X(_134_)
  );
  sg13g2_xor2_1 _186_ (
    .A(_132_),
    .B(_134_),
    .X(\DPATH.SUM.fa_2.S )
  );
  sg13g2_a21oi_1 _187_ (
    .A1(_132_),
    .A2(_134_),
    .B1(_133_),
    .Y(_135_)
  );
  sg13g2_nand2_1 _188_ (
    .A(\DPATH.SUM.fa_3.A ),
    .B(\CTRL.S0 ),
    .Y(_136_)
  );
  sg13g2_xnor2_1 _189_ (
    .A(\DPATH.SUM.fa_3.A ),
    .B(\CTRL.S0 ),
    .Y(_137_)
  );
  sg13g2_xor2_1 _190_ (
    .A(_135_),
    .B(_137_),
    .X(\DPATH.SUM.fa_3.S )
  );
  sg13g2_and2_1 _191_ (
    .A(\DPATH.SUM.fa_4.A ),
    .B(\CTRL.S0 ),
    .X(_009_)
  );
  sg13g2_xor2_1 _192_ (
    .A(\DPATH.SUM.fa_4.A ),
    .B(\CTRL.S0 ),
    .X(_010_)
  );
  sg13g2_o21ai_1 _193_ (
    .A1(_135_),
    .A2(_137_),
    .B1(_136_),
    .Y(_011_)
  );
  sg13g2_xor2_1 _194_ (
    .A(_010_),
    .B(_011_),
    .X(\DPATH.SUM.fa_4.S )
  );
  sg13g2_nand2_1 _195_ (
    .A(\DPATH.SUM.fa_5.A ),
    .B(\CTRL.S0 ),
    .Y(_012_)
  );
  sg13g2_xnor2_1 _196_ (
    .A(\DPATH.SUM.fa_5.A ),
    .B(\CTRL.S0 ),
    .Y(_013_)
  );
  sg13g2_a21oi_1 _197_ (
    .A1(_010_),
    .A2(_011_),
    .B1(_009_),
    .Y(_014_)
  );
  sg13g2_xor2_1 _198_ (
    .A(_013_),
    .B(_014_),
    .X(\DPATH.SUM.fa_5.S )
  );
  sg13g2_o21ai_1 _199_ (
    .A1(_013_),
    .A2(_014_),
    .B1(_012_),
    .Y(_015_)
  );
  sg13g2_xnor2_1 _200_ (
    .A(\CTRL.S0 ),
    .B(\DPATH.SUM.fa_6.A ),
    .Y(_016_)
  );
  sg13g2_xnor2_1 _201_ (
    .A(_015_),
    .B(_016_),
    .Y(\DPATH.SUM.fa_6.S )
  );
  sg13g2_nand3b_1 _202_ (
    .A_N(\DPATH.SUM.fa_1.A ),
    .B(\DPATH.SUM.Cout0 ),
    .C(\CTRL.S0 ),
    .Y(_017_)
  );
  sg13g2_nor3_1 _203_ (
    .A(_103_),
    .B(_129_),
    .C(_017_),
    .Y(_018_)
  );
  sg13g2_xnor2_1 _204_ (
    .A(signB),
    .B(_018_),
    .Y(\CTRL.P1 )
  );
  sg13g2_nor3_1 _205_ (
    .A(\DPATH.SUM.Cout0 ),
    .B(_109_),
    .C(_124_),
    .Y(_019_)
  );
  sg13g2_a21oi_1 _206_ (
    .A1(\DPATH.SUM.fa_6.A ),
    .A2(_019_),
    .B1(\CTRL.S0 ),
    .Y(_020_)
  );
  sg13g2_nor2_1 _207_ (
    .A(_018_),
    .B(_020_),
    .Y(\CTRL.P0 )
  );
  sg13g2_and2_1 _208_ (
    .A(_115_),
    .B(_119_),
    .X(_021_)
  );
  sg13g2_nand2_1 _209_ (
    .A(_115_),
    .B(_119_),
    .Y(_022_)
  );
  sg13g2_nor2_1 _210_ (
    .A(\DPATH.SUM.fa_3.A ),
    .B(_021_),
    .Y(_023_)
  );
  sg13g2_nand2_1 _211_ (
    .A(\DPATH.SUM.Cout0 ),
    .B(_112_),
    .Y(_024_)
  );
  sg13g2_xor2_1 _212_ (
    .A(\DPATH.SUM.fa_1.A ),
    .B(\DPATH.SUM.Cout0 ),
    .X(_025_)
  );
  sg13g2_or2_1 _213_ (
    .A(_102_),
    .B(_025_),
    .X(_026_)
  );
  sg13g2_and3_1 _214_ (
    .A(\DPATH.SUM.fa_3.A ),
    .B(_024_),
    .C(_026_),
    .X(_027_)
  );
  sg13g2_o21ai_1 _215_ (
    .A1(_023_),
    .A2(_027_),
    .B1(\DPATH.SUM.fa_4.A ),
    .Y(_028_)
  );
  sg13g2_nand2_1 _216_ (
    .A(_102_),
    .B(\DPATH.SUM.fa_1.A ),
    .Y(_029_)
  );
  sg13g2_a21oi_1 _217_ (
    .A1(\DPATH.SUM.fa_1.A ),
    .A2(\DPATH.SUM.Cout0 ),
    .B1(\DPATH.SUM.fa_3.A ),
    .Y(_030_)
  );
  sg13g2_nor3_1 _218_ (
    .A(\DPATH.SUM.fa_4.A ),
    .B(_022_),
    .C(_030_),
    .Y(_031_)
  );
  sg13g2_a21oi_1 _219_ (
    .A1(_023_),
    .A2(_029_),
    .B1(_031_),
    .Y(_032_)
  );
  sg13g2_a21oi_1 _220_ (
    .A1(_028_),
    .A2(_032_),
    .B1(\DPATH.SUM.fa_5.A ),
    .Y(_033_)
  );
  sg13g2_nor2_1 _221_ (
    .A(_101_),
    .B(\DPATH.SUM.fa_4.A ),
    .Y(_034_)
  );
  sg13g2_nand2b_1 _222_ (
    .A_N(\DPATH.SUM.fa_4.A ),
    .B(\DPATH.SUM.fa_5.A ),
    .Y(_035_)
  );
  sg13g2_nor2_1 _223_ (
    .A(\DPATH.SUM.fa_3.A ),
    .B(\DPATH.SUM.fa_1.A ),
    .Y(_036_)
  );
  sg13g2_nor2_1 _224_ (
    .A(_112_),
    .B(_120_),
    .Y(_037_)
  );
  sg13g2_xnor2_1 _225_ (
    .A(\DPATH.SUM.fa_2.A ),
    .B(\DPATH.SUM.fa_1.A ),
    .Y(_038_)
  );
  sg13g2_a21oi_1 _226_ (
    .A1(_107_),
    .A2(_113_),
    .B1(_100_),
    .Y(_039_)
  );
  sg13g2_or2_1 _227_ (
    .A(_036_),
    .B(_039_),
    .X(_040_)
  );
  sg13g2_nand2_1 _228_ (
    .A(\DPATH.SUM.fa_4.A ),
    .B(_128_),
    .Y(_041_)
  );
  sg13g2_nand3_1 _229_ (
    .A(\DPATH.SUM.fa_4.A ),
    .B(\DPATH.SUM.fa_1.A ),
    .C(\DPATH.SUM.Cout0 ),
    .Y(_042_)
  );
  sg13g2_nand2_1 _230_ (
    .A(\DPATH.SUM.fa_3.A ),
    .B(_117_),
    .Y(_043_)
  );
  sg13g2_a21oi_1 _231_ (
    .A1(_041_),
    .A2(_042_),
    .B1(_101_),
    .Y(_044_)
  );
  sg13g2_a221oi_1 _232_ (
    .A1(_034_),
    .A2(_040_),
    .B1(_043_),
    .B2(_044_),
    .C1(_033_),
    .Y(_045_)
  );
  sg13g2_a21oi_1 _233_ (
    .A1(\DPATH.SUM.Cout0 ),
    .A2(_037_),
    .B1(_105_),
    .Y(_046_)
  );
  sg13g2_nand2_1 _234_ (
    .A(_126_),
    .B(_046_),
    .Y(_047_)
  );
  sg13g2_a21oi_1 _235_ (
    .A1(\DPATH.SUM.fa_3.A ),
    .A2(\DPATH.SUM.fa_1.A ),
    .B1(\DPATH.SUM.fa_4.A ),
    .Y(_048_)
  );
  sg13g2_o21ai_1 _236_ (
    .A1(\DPATH.SUM.fa_5.A ),
    .A2(_048_),
    .B1(_047_),
    .Y(_049_)
  );
  sg13g2_nand3_1 _237_ (
    .A(\DPATH.SUM.fa_4.A ),
    .B(_124_),
    .C(_025_),
    .Y(_050_)
  );
  sg13g2_nand2_1 _238_ (
    .A(_049_),
    .B(_050_),
    .Y(_051_)
  );
  sg13g2_nand3b_1 _239_ (
    .A_N(_105_),
    .B(_024_),
    .C(_026_),
    .Y(_052_)
  );
  sg13g2_and2_1 _240_ (
    .A(_100_),
    .B(_052_),
    .X(_053_)
  );
  sg13g2_nor3_1 _241_ (
    .A(_027_),
    .B(_035_),
    .C(_053_),
    .Y(_054_)
  );
  sg13g2_o21ai_1 _242_ (
    .A1(\DPATH.SUM.Cout0 ),
    .A2(_038_),
    .B1(_119_),
    .Y(_055_)
  );
  sg13g2_nor2b_1 _243_ (
    .A(_055_),
    .B_N(_024_),
    .Y(_056_)
  );
  sg13g2_nor2_1 _244_ (
    .A(_100_),
    .B(_107_),
    .Y(_057_)
  );
  sg13g2_nor3_1 _245_ (
    .A(_109_),
    .B(_056_),
    .C(_057_),
    .Y(_058_)
  );
  sg13g2_nor4_1 _246_ (
    .A(\DPATH.SUM.fa_6.A ),
    .B(_019_),
    .C(_054_),
    .D(_058_),
    .Y(_059_)
  );
  sg13g2_a22oi_1 _247_ (
    .A1(\DPATH.SUM.fa_6.A ),
    .A2(_045_),
    .B1(_051_),
    .B2(_059_),
    .Y(sine_out[0])
  );
  sg13g2_a22oi_1 _248_ (
    .A1(_121_),
    .A2(_023_),
    .B1(_056_),
    .B2(\DPATH.SUM.fa_3.A ),
    .Y(_060_)
  );
  sg13g2_a221oi_1 _249_ (
    .A1(_119_),
    .A2(_027_),
    .B1(_036_),
    .B2(_021_),
    .C1(_122_),
    .Y(_061_)
  );
  sg13g2_nor2_1 _250_ (
    .A(_109_),
    .B(_061_),
    .Y(_062_)
  );
  sg13g2_nand3_1 _251_ (
    .A(_100_),
    .B(\DPATH.SUM.fa_1.A ),
    .C(\DPATH.SUM.Cout0 ),
    .Y(_063_)
  );
  sg13g2_a21oi_1 _252_ (
    .A1(_021_),
    .A2(_063_),
    .B1(_125_),
    .Y(_064_)
  );
  sg13g2_nor2b_1 _253_ (
    .A(\DPATH.SUM.fa_5.A ),
    .B_N(\DPATH.SUM.fa_4.A ),
    .Y(_065_)
  );
  sg13g2_nand2_1 _254_ (
    .A(_055_),
    .B(_065_),
    .Y(_066_)
  );
  sg13g2_o21ai_1 _255_ (
    .A1(_035_),
    .A2(_060_),
    .B1(_066_),
    .Y(_067_)
  );
  sg13g2_nor4_1 _256_ (
    .A(\DPATH.SUM.fa_6.A ),
    .B(_062_),
    .C(_064_),
    .D(_067_),
    .Y(_068_)
  );
  sg13g2_a21oi_1 _257_ (
    .A1(_026_),
    .A2(_029_),
    .B1(\DPATH.SUM.fa_3.A ),
    .Y(_069_)
  );
  sg13g2_o21ai_1 _258_ (
    .A1(_039_),
    .A2(_069_),
    .B1(_065_),
    .Y(_070_)
  );
  sg13g2_nor2_1 _259_ (
    .A(_100_),
    .B(_046_),
    .Y(_071_)
  );
  sg13g2_a21oi_1 _260_ (
    .A1(_113_),
    .A2(_025_),
    .B1(\DPATH.SUM.fa_3.A ),
    .Y(_072_)
  );
  sg13g2_nor3_1 _261_ (
    .A(_125_),
    .B(_071_),
    .C(_072_),
    .Y(_073_)
  );
  sg13g2_nor2_1 _262_ (
    .A(\DPATH.SUM.fa_3.A ),
    .B(_102_),
    .Y(_074_)
  );
  sg13g2_nor3_1 _263_ (
    .A(\DPATH.SUM.fa_4.A ),
    .B(_057_),
    .C(_074_),
    .Y(_075_)
  );
  sg13g2_nand3_1 _264_ (
    .A(\DPATH.SUM.fa_5.A ),
    .B(_041_),
    .C(_042_),
    .Y(_076_)
  );
  sg13g2_o21ai_1 _265_ (
    .A1(_075_),
    .A2(_076_),
    .B1(\DPATH.SUM.fa_6.A ),
    .Y(_077_)
  );
  sg13g2_nor2_1 _266_ (
    .A(_073_),
    .B(_077_),
    .Y(_078_)
  );
  sg13g2_a21oi_1 _267_ (
    .A1(_070_),
    .A2(_078_),
    .B1(_068_),
    .Y(sine_out[1])
  );
  sg13g2_and2_1 _268_ (
    .A(_029_),
    .B(_042_),
    .X(_079_)
  );
  sg13g2_o21ai_1 _269_ (
    .A1(\DPATH.SUM.fa_4.A ),
    .A2(_026_),
    .B1(_079_),
    .Y(_080_)
  );
  sg13g2_a21oi_1 _270_ (
    .A1(_100_),
    .A2(_080_),
    .B1(\DPATH.SUM.fa_5.A ),
    .Y(_081_)
  );
  sg13g2_o21ai_1 _271_ (
    .A1(_100_),
    .A2(_080_),
    .B1(_081_),
    .Y(_082_)
  );
  sg13g2_a21oi_1 _272_ (
    .A1(_107_),
    .A2(_113_),
    .B1(\DPATH.SUM.fa_3.A ),
    .Y(_083_)
  );
  sg13g2_or2_1 _273_ (
    .A(\DPATH.SUM.fa_4.A ),
    .B(_083_),
    .X(_084_)
  );
  sg13g2_and3_1 _274_ (
    .A(\DPATH.SUM.fa_3.A ),
    .B(_115_),
    .C(_037_),
    .X(_085_)
  );
  sg13g2_o21ai_1 _275_ (
    .A1(\DPATH.SUM.fa_2.A ),
    .A2(_105_),
    .B1(_030_),
    .Y(_086_)
  );
  sg13g2_o21ai_1 _276_ (
    .A1(_100_),
    .A2(_038_),
    .B1(_086_),
    .Y(_087_)
  );
  sg13g2_o21ai_1 _277_ (
    .A1(_084_),
    .A2(_085_),
    .B1(\DPATH.SUM.fa_5.A ),
    .Y(_088_)
  );
  sg13g2_a21oi_1 _278_ (
    .A1(\DPATH.SUM.fa_4.A ),
    .A2(_087_),
    .B1(_088_),
    .Y(_089_)
  );
  sg13g2_nor2_1 _279_ (
    .A(\DPATH.SUM.fa_6.A ),
    .B(_089_),
    .Y(_090_)
  );
  sg13g2_nand3_1 _280_ (
    .A(\DPATH.SUM.fa_1.A ),
    .B(\DPATH.SUM.Cout0 ),
    .C(_074_),
    .Y(_091_)
  );
  sg13g2_and2_1 _281_ (
    .A(\DPATH.SUM.fa_4.A ),
    .B(_091_),
    .X(_092_)
  );
  sg13g2_o21ai_1 _282_ (
    .A1(_106_),
    .A2(_069_),
    .B1(_092_),
    .Y(_093_)
  );
  sg13g2_nor2_1 _283_ (
    .A(_120_),
    .B(_084_),
    .Y(_094_)
  );
  sg13g2_a21oi_1 _284_ (
    .A1(_117_),
    .A2(_094_),
    .B1(\DPATH.SUM.fa_5.A ),
    .Y(_095_)
  );
  sg13g2_nand2_1 _285_ (
    .A(_128_),
    .B(_034_),
    .Y(_096_)
  );
  sg13g2_o21ai_1 _286_ (
    .A1(_057_),
    .A2(_096_),
    .B1(\DPATH.SUM.fa_6.A ),
    .Y(_097_)
  );
  sg13g2_a21oi_1 _287_ (
    .A1(_093_),
    .A2(_095_),
    .B1(_097_),
    .Y(_098_)
  );
  sg13g2_a21oi_1 _288_ (
    .A1(_082_),
    .A2(_090_),
    .B1(_098_),
    .Y(sine_out[2])
  );
  sg13g2_nor2_1 _289_ (
    .A(_103_),
    .B(_108_),
    .Y(sine_out[3])
  );
  sg13g2_nor3_1 _290_ (
    .A(\DPATH.SUM.fa_4.A ),
    .B(_103_),
    .C(_114_),
    .Y(sine_out[4])
  );
  sg13g2_nor2_1 _291_ (
    .A(\DPATH.SUM.ha_0.S ),
    .B(_124_),
    .Y(_099_)
  );
  sg13g2_nor3_1 _292_ (
    .A(\DPATH.SUM.fa_4.A ),
    .B(_103_),
    .C(_099_),
    .Y(sine_out[5])
  );
  sg13g2_a21oi_1 _293_ (
    .A1(\DPATH.SUM.fa_4.A ),
    .A2(_128_),
    .B1(_103_),
    .Y(sine_out[6])
  );
  sg13g2_a21oi_1 _294_ (
    .A1(\DPATH.SUM.fa_4.A ),
    .A2(_114_),
    .B1(_103_),
    .Y(sine_out[7])
  );
  sg13g2_a21oi_1 _295_ (
    .A1(\DPATH.SUM.fa_4.A ),
    .A2(_099_),
    .B1(_103_),
    .Y(sine_out[8])
  );
  sg13g2_inv_1 _296_ (
    .A(rst),
    .Y(_001_)
  );
  sg13g2_inv_1 _297_ (
    .A(rst),
    .Y(_002_)
  );
  sg13g2_inv_1 _298_ (
    .A(rst),
    .Y(_003_)
  );
  sg13g2_inv_1 _299_ (
    .A(rst),
    .Y(_004_)
  );
  sg13g2_inv_1 _300_ (
    .A(rst),
    .Y(_005_)
  );
  sg13g2_inv_1 _301_ (
    .A(rst),
    .Y(_006_)
  );
  sg13g2_inv_1 _302_ (
    .A(rst),
    .Y(_007_)
  );
  sg13g2_inv_1 _303_ (
    .A(rst),
    .Y(_008_)
  );
  sg13g2_dfrbpq_1 _304_ (
    .CLK(clk),
    .D(\DPATH.SUM.ha_0.S ),
    .Q(\DPATH.SUM.Cout0 ),
    .RESET_B(_000_)
  );
  sg13g2_dfrbpq_1 _305_ (
    .CLK(clk),
    .D(\DPATH.SUM.fa_1.S ),
    .Q(\DPATH.SUM.fa_1.A ),
    .RESET_B(_001_)
  );
  sg13g2_dfrbpq_1 _306_ (
    .CLK(clk),
    .D(\DPATH.SUM.fa_2.S ),
    .Q(\DPATH.SUM.fa_2.A ),
    .RESET_B(_002_)
  );
  sg13g2_dfrbpq_1 _307_ (
    .CLK(clk),
    .D(\DPATH.SUM.fa_3.S ),
    .Q(\DPATH.SUM.fa_3.A ),
    .RESET_B(_003_)
  );
  sg13g2_dfrbpq_1 _308_ (
    .CLK(clk),
    .D(\DPATH.SUM.fa_4.S ),
    .Q(\DPATH.SUM.fa_4.A ),
    .RESET_B(_004_)
  );
  sg13g2_dfrbpq_1 _309_ (
    .CLK(clk),
    .D(\DPATH.SUM.fa_5.S ),
    .Q(\DPATH.SUM.fa_5.A ),
    .RESET_B(_005_)
  );
  sg13g2_dfrbpq_1 _310_ (
    .CLK(clk),
    .D(\DPATH.SUM.fa_6.S ),
    .Q(\DPATH.SUM.fa_6.A ),
    .RESET_B(_006_)
  );
  sg13g2_dfrbpq_1 _311_ (
    .CLK(clk),
    .D(\CTRL.P1 ),
    .Q(sign),
    .RESET_B(_007_)
  );
  sg13g2_dfrbpq_1 _312_ (
    .CLK(clk),
    .D(\CTRL.P0 ),
    .Q(\CTRL.S0 ),
    .RESET_B(_008_)
  );
endmodule
